# Site settings
name: ahmed
email: ahmedBughra@gmail.com
url: "https://uycoder.github.io"
description: "پايدىلىق بىلىملەر ۋە پىكىرلەر"
author: "A. Bughra"
title: "پايدىلار بلوگى"
permalink: pretty
baseurl: /paydilar
logo: /paydilar/Biliklogo.png

# social
github:
  username: UyCoder

twitter:
  username: ahmedBughra