# Site settings
name: ahmed
email: ahmedBughra@gmail.com
url: url
description: "A blog and a portfolio"
author: "A. Bughra"
title: "پايدىلار بلوگى"
permalink: pretty
baseurl: /paydilar

# social
github:
  username: UyCoder

twitter:
  username: ahmedBughra