window.hezine_english = [
  // 1-3: سىز تەمىنلىگەن ئاساسىي جۈملىلەر
  { "text": "The only limit to our realization of tomorrow will be our doubts of today.", "translation": "ئەتە كەلگۈسىمىزنى رېئاللىققا ئايلاندۇرۇشتىكى بىردىنبىر توسالغۇ، بىزنىڭ بۈگۈنكى گۇمانىمىزدۇر." },
  { "text": "Do what you can, with what you have, where you are.", "translation": "قولۇڭدىن كېلىدىغاننى قىل، بار نەرسەڭ بىلەن، تۇرغان جايىڭدا." },
  { "text": "In the middle of difficulty lies opportunity.", "translation": "قىيىنچىلىقنىڭ ئوتتۇرىسىدا پۇرسەت يوشۇرۇنغاندۇر." },

  // 4-20: ئارزۇ، ئىشەنچ ۋە مۇۋەپپەقىيەت
  { "text": "Believe you can and you're halfway there.", "translation": "ئۆزىڭىزنىڭ قىلالايدىغانلىقىڭىزغا ئىشىنىڭ، شۇنداق قىلسىڭىز يېرىم يولنى باسقان بولىسىز." },
  { "text": "It always seems impossible until it's done.", "translation": "بىر ئىش قىلىپ پۈتتۈرۈلمىگۈچە، ئۇ ھەمىشە مۇمكىن بولمايدىغاندەك بىلىنىدۇ." },
  { "text": "The future belongs to those who believe in the beauty of their dreams.", "translation": "كەلگۈسى ئۆز ئارزۇلىرىنىڭ گۈزەللىكىگە ئىشىنىدىغانلارغا مەنسۇپتۇر." },
  { "text": "Success is not final, failure is not fatal: it is the courage to continue that counts.", "translation": "مۇۋەپپەقىيەت ئاخىرقى نۇقتا ئەمەس، مەغلۇبىيەتمۇ ئەجەللىك ئەمەس: ئەڭ مۇھىمى داۋاملاشتۇرۇش جەسارىتىدۇر." },
  { "text": "Don't watch the clock; do what it does. Keep going.", "translation": "سائەتكە قاراپ ئولتۇرماڭ؛ ئۇ نېمە قىلسا شۇنى قىلىڭ، يەنى داۋاملىق ئىلگىرىلەڭ." },
  { "text": "The secret of getting ahead is getting started.", "translation": "ئالدىغا ئۆتۈپ كېتىشنىڭ سىرى، ھەرىكەتنى باشلاشتۇر." },
  { "text": "You miss 100% of the shots you don't take.", "translation": "سىز سىناپ باقمىغان پۇرسەتلەرنىڭ 100 پىرسەنتىنى قولدىن بېرىپ قويىسىز." },
  { "text": "Whether you think you can or you think you can't, you're right.", "translation": "مەيلى سىز ئۆزىڭىزنى قىلالايمەن دەپ ئويلاڭ ياكى قىلالمايمەن دەپ ئويلاڭ، ھەر ئىككىلىسىدە سىزنىڭكى توغرا (چۈنكى نەتىجە ئويىڭىزغا ئەگىشىدۇ)." },
  { "text": "I find that the harder I work, the more luck I seem to have.", "translation": "مەن شۇنى بايقىدىمكى، قانچە تىرىشىپ ئىشلىسەم، تەلېيىم شۇنچە ئوڭىدىن كېلىدىكەن." },
  { "text": "Opportunities don't happen. You create them.", "translation": "پۇرسەتلەر ئۆزلۈكىدىن كەلمەيدۇ، ئۇنى سىز يارىتىسىز." },
  { "text": "Don't be afraid to give up the good to go for the great.", "translation": "ئەڭ ياخشىسىغا ئېرىشىش ئۈچۈن، ياخشىسىدىن ۋاز كېچىشتىن قورقماڭ." },
  { "text": "Action is the foundational key to all success.", "translation": "ھەرىكەت قىلىش — بارلىق مۇۋەپپەقىيەتلەرنىڭ ئەڭ ئاساسلىق ئاچقۇچىدۇر." },
  { "text": "Dream big and dare to fail.", "translation": "ئارزۇيۇڭ چوڭ بولسۇن ۋە مەغلۇپ بولۇشتىن قورقما." },
  { "text": "The only place where success comes before work is in the dictionary.", "translation": "مۇۋەپپەقىيەت (Success) نىڭ مېھنەت (Work) تىن بۇرۇن كېلىدىغان بىردىنبىر يېرى پەقەت لۇغەتتىلا بار (ھەرپلەرنىڭ تەرتىپى بويىچە)." },
  { "text": "Go confidently in the direction of your dreams. Live the life you have imagined.", "translation": "ئارزۇلىرىڭىز يۆنىلىشىگە قاراپ ئىشەنچ بىلەن قەدەم تاشلاڭ. ئۆزىڭىز تەسەۋۋۇر قىلغان ھاياتنى ياشاڭ." },
  { "text": "Strive not to be a success, but rather to be of value.", "translation": "مۇۋەپپەقىيەت قازىنىش ئۈچۈن ئەمەس، بەلكى قىممەت يارىتىش ئۈچۈن تىرىشىڭ." },

  // 21-40: تىرىشچانلىق، كۈچ ۋە يېڭىلمەس روھ
  { "text": "Fall seven times and stand up eight.", "translation": "يەتتە قېتىم يىقىلسىڭمۇ، سەككىزىنچى قېتىم ئورنۇڭدىن تۇر." },
  { "text": "Hard work beats talent when talent doesn't work hard.", "translation": "تالانت تىرىشمىغاندا، تىرىشچانلىق تالانتنى يېڭىدۇ." },
  { "text": "It does not matter how slowly you go as long as you do not stop.", "translation": "توختاپ قالمىسىڭىزلا، قانچىلىك ئاستا مېڭىشىڭىزنىڭ ھېچقانداق ئەھمىيىتى يوق." },
  { "text": "Tough times never last, but tough people do.", "translation": "قىيىن كۈنلەر مەڭگۈ داۋاملاشمايدۇ، ئەمما ئىرادىسى كۈچلۈك كىشىلەر مەڭگۈ داۋاملىشىدۇ." },
  { "text": "Everything you've ever wanted is on the other side of fear.", "translation": "سىز ئارزۇ قىلغان ھەممە نەرسە قورقۇنچنىڭ ئارقا تەرىپىگە يوشۇرۇنغان." },
  { "text": "Pain is temporary. Quitting lasts forever.", "translation": "ئازاب ۋاقىتلىق بولىدۇ، ئەمما ۋاز كېچىش مەڭگۈلۈكتۇر." },
  { "text": "A smooth sea never made a skilled sailor.", "translation": "تېنچ دېڭىز ھەرگىزمۇ قابىلىيەتلىك دېڭىزچىنى يېتىشتۈرۈپ چىقالمايدۇ." },
  { "text": "Don't pray for an easy life, pray for the strength to endure a difficult one.", "translation": "ئاسان بىر ھاياتنى تىلىمەڭ، بەلكى قىيىن ھاياتقا بەرداشلىق بېرەلەيدىغان كۈچنى تىلەڭ." },
  { "text": "Stars can't shine without darkness.", "translation": "قاراڭغۇلۇق بولمىسا يۇلتۇزلار چاقنىيالمايدۇ." },
  { "text": "Sometimes you win, sometimes you learn.", "translation": "بەزىدە غەلىبە قىلىسىز، بەزىدە بولسا (ساۋاق) ئۆگىنىسىز." },
  { "text": "A winner is a dreamer who never gives up.", "translation": "غەلىبە قىلغۇچى — ئەسلىدە ھەرگىز تەسلىم بولمايدىغان ئارزۇگەر كىشىدۇر." },
  { "text": "Work hard in silence, let your success be your noise.", "translation": "سۈكۈت ئىچىدە جاپا چېكىپ ئىشلەڭ، غەلىبىڭىز سىزنىڭ ئاۋازىڭىز بولسۇن." },
  { "text": "The pain you feel today will be the strength you feel tomorrow.", "translation": "سىز بۈگۈن ھېس قىلغان ئازاب، سىزنىڭ ئەتە ھېس قىلىدىغان كۈچىڭىزگە ئايلىنىدۇ." },
  { "text": "Push yourself, because no one else is going to do it for you.", "translation": "ئۆز-ئۆزىڭىزنى قىستاڭ (ھەرىكەتلەندۈرۈڭ)، چۈنكى باشقا ھېچكىم بۇنى سىز ئۈچۈن قىلىپ بەرمەيدۇ." },
  { "text": "Great things never come from comfort zones.", "translation": "ئۇلۇغ ئىشلار ھەرگىزمۇ راھەت رايوندىن (ياتياقلىقتىن) چىقمايدۇ." },
  { "text": "If it doesn't challenge you, it doesn't change you.", "translation": "ئەگەر بىر ئىش سىزگە خىرىس قىلالمىسا، ئۇ سىزنى ئۆزگەرتەلمەيدۇ." },
  { "text": "Doubt kills more dreams than failure ever will.", "translation": "مەغلۇبىيەتكە قارىغاندا، گۇمان قىلىش تېخىمۇ كۆپ ئارزۇلارنى ۋەيران قىلىدۇ." },
  { "text": "Keep your face always toward the sunshine—and shadows will fall behind you.", "translation": "يۈزىڭىزنى ھەمىشە قۇياش نۇرىغا قاراتسىڭىز، كۆلەڭگىلەر كەينىڭىزدە قالىدۇ." },
  { "text": "What does not kill me makes me stronger.", "translation": "مېنى ئۆلتۈرەلمىگەن ھەرقانداق نەرسە مېنى تېخىمۇ كۈچلۈك قىلىدۇ." },
  { "text": "The harder the conflict, the more glorious the triumph.", "translation": "توقۇنۇش (قىيىنچىلىق) قانچە شىددەتلىك بولسا، غەلىبە شۇنچە شانلىق بولىدۇ." },

  // 41-60: ھايات پەلسەپىسى ۋە ۋاقىت
  { "text": "Life is what happens when you're busy making other plans.", "translation": "ھايات دېگەن سىز باشقا پىلانلارنى تۈزۈش بىلەن ئالدىراش بولۇۋاتقاندا، سىزنىڭ بېشىڭىزدىن ئۆتۈۋاتقان جەرياندۇر." },
  { "text": "Your time is limited, so don't waste it living someone else's life.", "translation": "ۋاقتىڭىز چەكلىك، شۇڭا ئۇنى باشقىلارنىڭ ھاياتىنى ياشاش ئۈچۈن ئىسراپ قىلماڭ." },
  { "text": "Yesterday is history, tomorrow is a mystery, today is a gift. That's why it is called the present.", "translation": "تۈنۈگۈن بىر تارىخ، ئەتە بىر سىر، بۈگۈن بولسا بىر سوۋغاتتۇر. شۇڭلاشقا ئۇ «نۆۋەت» (سوۋغات) دەپ ئاتىلىدۇ." },
  { "text": "In three words I can sum up everything I've learned about life: it goes on.", "translation": "مەن ھاياتتىن ئۆگەنگەن ھەممە نەرسىنى ئۈچلا سۆزگە يىغىنچاقلايمەن: ھايات داۋام قىلىدۇ." },
  { "text": "To live is the rarest thing in the world. Most people exist, that is all.", "translation": "دۇنيادا ھەقىقىي ياشاش ئەڭ ئاز ئۇچرايدىغان ئىشتۇر. كۆپىنچە كىشىلەر پەقەتلا مەۋجۇت بولۇپ تۇرىدۇ، خالاس." },
  { "text": "The unexamined life is not worth living.", "translation": "ئويلانماي (ئۆز-ئۆزىنى تەكشۈرمەي) ئۆتكۈزگەن ھاياتنىڭ ياشاش قىممىتى يوق." },
  { "text": "Turn your wounds into wisdom.", "translation": "يارىلىرىڭىزنى ئەقىل-پاراسەتكە ئايلاندۇرۇڭ." },
  { "text": "Be the change that you wish to see in the world.", "translation": "دۇنيادا كۆرمەكچى بولغان ئۆزگىرىشنىڭ ئۆزى بولۇڭ." },
  { "text": "Life is really simple, but we insist on making it complicated.", "translation": "ئەسلىدە ھايات ئىنتايىن ئاددىي، ئەمما بىز ئۇنى مۇرەككەپلەشتۈرۈۋېلىشتا چىڭ تۇرىمىز." },
  { "text": "The purpose of our lives is to be happy.", "translation": "ھاياتىمىزنىڭ مەقسىتى بەختلىك بولۇشتۇر." },
  { "text": "Time is money.", "translation": "ۋاقىت دېگەن پۇل (ئالتۇن) دۇر." },
  { "text": "Lost time is never found again.", "translation": "ئىسراپ بولغان ۋاقىت قايتا تېپىلمايدۇ." },
  { "text": "The two most powerful warriors are patience and time.", "translation": "ئەڭ كۈچلۈك ئىككى جەڭچى بولسا — سەۋر ۋە ۋاقىتتۇر." },
  { "text": "Life is a journey, not a destination.", "translation": "ھايات بىر سەپەر، ئۇ ئاخىرقى مەنزىل ئەمەس." },
  { "text": "He who has a why to live for can bear almost any how.", "translation": "ياشاش ئۈچۈن بىر سەۋەبى (مەقسىتى) بار ئادەم، ھەر قانداق قىيىنچىلىققا بەرداشلىق بېرەلەيدۇ." },
  { "text": "Experience is a hard teacher because she gives the test first, the lesson afterwards.", "translation": "تەجرىبە ئىنتايىن شەپقەتسىز ئۇستازدۇر، چۈنكى ئۇ ئاۋۋال ئىمتىھان ئالىدۇ، ئاندىن ساۋاق بېرىدۇ." },
  { "text": "The only constant in life is change.", "translation": "ھاياتتىكى ئۆزگەرمەيدىغان بىردىنبىر نەرسە — ئۆزگىرىشتۇر." },
  { "text": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "translation": "بىزنىڭ كىملىكىمىز قايتا-قايتا قىلغان ئىشلىرىمىزدىن بىلىنىدۇ. دېمەككى، مۇنەۋۋەرلىك بىر قېتىملىق قىلمىش ئەمەس، بەلكى بىر ئادەتتۇر." },
  { "text": "The mind is everything. What you think you become.", "translation": "زېھىن (ئوي-خىيال) ھەممە نەرسىدۇر. سىز نېمىنى ئويلىسىڭىز، شۇنىڭغا ئايلانىسىز." },
  { "text": "A journey of a thousand miles begins with a single step.", "translation": "مىڭ چاقىرىملىق مۇساپىمۇ بىر قەدەمدىن باشلىنىدۇ." },

  // 61-80: بىلىم، خاراكتېر ۋە كىشىلىك مۇناسىۋەت
  { "text": "Knowledge is power.", "translation": "بىلىم — كۈچتۇر." },
  { "text": "An investment in knowledge pays the best interest.", "translation": "بىلىمگە سېلىنغان مەبلەغ ئەڭ يۇقىرى پايدا قايتۇرىدۇ." },
  { "text": "Education is the most powerful weapon which you can use to change the world.", "translation": "مائارىپ سىز دۇنيانى ئۆزگەرتىش ئۈچۈن ئىشلىتەلەيدىغان ئەڭ قۇدرەتلىك قورالدۇر." },
  { "text": "Stay hungry, stay foolish.", "translation": "بىلىمگە ھەمىشە ئاچ، ئۆگىنىش ئالدىدا ھەمىشە نادان (كەمتەر) بول." },
  { "text": "Respect yourself and others will respect you.", "translation": "ئۆزۈڭنى ھۆرمەت قىل، شۇنداق قىلسىڭىز باشقىلارمۇ سىزنى ھۆرمەت قىلىدۇ." },
  { "text": "A friend is someone who knows all about you and still loves you.", "translation": "دوست دېگەن سىز توغرىلىق ھەممىنى بىلىدىغان، لېكىن يەنىلا سىزنى ياخشى كۆرىدىغان كىشىدۇر." },
  { "text": "No one can make you feel inferior without your consent.", "translation": "سىزنىڭ قوشۇلۇشىڭىزسىز ھېچكىم سىزنى ئۆزىڭىزنى تۆۋەن كۆرىدىغان قىلالمايدۇ." },
  { "text": "If you judge people, you have no time to love them.", "translation": "ئەگەر ئادەملەرگە باھا بېرىش بىلەنلا ئالدىراش بولسىڭىز، ئۇلارنى ياخشى كۆرۈشكە ۋاقتىڭىز قالمايدۇ." },
  { "text": "Honesty is the first chapter in the book of wisdom.", "translation": "سەمىمىيلىك ئەقىل-پاراسەت كىتابىنىڭ بىرىنچى بابىدۇر." },
  { "text": "You are the average of the five people you spend the most time with.", "translation": "سىز ئۆزىڭىز ئەڭ كۆپ بىللە بولىدىغان بەش ئادەمنىڭ ئوتتۇرىچە يىغىندىسىسىز." },
  { "text": "Kindness is a language which the deaf can hear and the blind can see.", "translation": "مېھرىبانلىق شۇنداق بىر تىلكى، ئۇنى گاسلارمۇ ئاڭلىيالايدۇ، كورلارمۇ كۆرەلەيدۇ." },
  { "text": "Love all, trust a few, do wrong to none.", "translation": "ھەممىنى ياخشى كۆر، ئاز ساندىكىسىگە ئىشەن، ھېچكىمگە يامانلىق قىلما." },
  { "text": "A lie can travel half way around the world while the truth is putting on its shoes.", "translation": "ھەقىقەت ئاياغلىرىنى كىيگۈچە، يالغانچىلىق دۇنيانىڭ يېرىمىنى ئايلىنىپ بولىدۇ." },
  { "text": "It takes courage to grow up and become who you really are.", "translation": "ئۆسۈپ يېتىلىش ۋە ئۆزىڭىزنىڭ ھەقىقىي كىملىكىگە ئايلىنىش ئۈچۈن جەسارەت كېرەك." },
  { "text": "Whatever you are, be a good one.", "translation": "نېمىلا بولماڭ، ئەڭ ياخشىسى بولۇڭ." },
  { "text": "Live as if you were to die tomorrow. Learn as if you were to live forever.", "translation": "ئەتە ئۆلىدىغاندەك ياشا، مەڭگۈ ياشايدىغاندەك ئۆگەن." },
  { "text": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "translation": "سىزنى توختىماي باشقا بىرىگە ئايلاندۇرۇشقا تىرىشىۋاتقان بۇ دۇنيادا ئۆز پېتى قېلىش — ئەڭ بۈيۈك نەتىجىدۇر." },
  { "text": "Be yourself; everyone else is already taken.", "translation": "ئۆزۈڭ بول، چۈنكى باشقا روللارنى ئاللىقاچان كىشىلەر ئېلىپ بولدى." },
  { "text": "I have not failed. I've just found 10,000 ways that won't work.", "translation": "مەن مەغلۇپ بولمىدىم، پەقەت ئىشلىمەيدىغان 10 مىڭ خىل ئۇسۇلنى بايقىدىم." },
  { "text": "A room without books is like a body without a soul.", "translation": "كىتابسىز ئۆي خۇددى روھسىز جەسەتكە ئوخشايدۇ." },

  // 81-100: خۇشاللىق، ئۈمىد ۋە ئۆزىگە ئىشىنىش
  { "text": "Happiness depends upon ourselves.", "translation": "بەخت-خۇشاللىق ئۆزىمىزگە باغلىقتۇر." },
  { "text": "The best way to cheer yourself is to try to cheer someone else up.", "translation": "ئۆزىڭىزنى خۇشال قىلىشنىڭ ئەڭ ياخشى ئۇسۇلى، باشقا بىرىنى خۇشال قىلىشقا تىرىشىشتۇر." },
  { "text": "Count your age by friends, not years. Count your life by smiles, not tears.", "translation": "يېشىڭىزنى يىل بىلەن ئەمەس، دوستلىرىڭىز بىلەن ھېسابلاڭ. ھاياتىڭىزنى كۆز يېشى بىلەن ئەمەس، كۈلكە بىلەن ھېسابلاڭ." },
  { "text": "Every day may not be good, but there is something good in every day.", "translation": "ھەر بىر كۈن ياخشى بولماسلىقى مۇمكىن، ئەمما ھەر بىر كۈندە ياخشى بىر نەرسە چوقۇم بولىدۇ." },
  { "text": "Once you choose hope, anything's possible.", "translation": "سىز ئۈمىدنى تاللىغان ھامان، ھەممە نەرسە مۇمكىن بولىدۇ." },
  { "text": "The most wasted of all days is one without laughter.", "translation": "بارلىق كۈنلەرنىڭ ئىچىدە ئەڭ ئىسراپ بولغىنى، كۈلكىسىز ئۆتكەن بىر كۈندۇر." },
  { "text": "Worry does not empty tomorrow of its sorrow, it empties today of its strength.", "translation": "غەم-قايغۇ ئەتىنىڭ ئازابىنى يوق قىلالمايدۇ، بەلكى بۈگۈننىڭ كۈچىنى يوقىتىدۇ." },
  { "text": "Let your smile change the world, but don't let the world change your smile.", "translation": "كۈلكىڭىز دۇنيانى ئۆزگەرتسۇن، ئەمما دۇنيانىڭ كۈلكىڭىزنى ئۆزگەرتىۋېتىشىگە يول قويماڭ." },
  { "text": "Love yourself first and everything else falls into line.", "translation": "ئاۋۋال ئۆزىڭىزنى سۆيۈڭ، ئاندىن باشقا ھەممە ئىش ئۆز ئىزىغا چۈشىدۇ." },
  { "text": "You are enough just as you are.", "translation": "سىز ھازىرقى ھالىتىڭىز بىلەنلا يېتەرلىكسىز (كامالەتتىسىز)." },
  { "text": "Be a voice, not an echo.", "translation": "ياڭراق ئاۋاز بولۇڭ، ئەكس سادا بولماڭ." },
  { "text": "Your only limit is your mind.", "translation": "سىزدىكى بىردىنبىر چەكلىمە پەقەت ئۆز زېھنىڭىزدۇر." },
  { "text": "Every morning we are born again. What we do today is what matters most.", "translation": "ھەر كۈنى سەھەردە بىز قايتا تۇغۇلىمىز. بۈگۈن نېمە ئىش قىلىشىمىز ئەڭ مۇھىم بولغىنىدۇر." },
  { "text": "Always do your best. What you plant now, you will harvest later.", "translation": "ھەمىشە پۈتۈن كۈچىڭىز بىلەن تىرىشىڭ. ھازىر نېمىنى تېرىسىڭىز، كېيىن شۇنىڭ ھوسۇلىنى ئالىسىز." },
  { "text": "Don't let yesterday take up too much of today.", "translation": "تۈنۈگۈننىڭ بۈگۈنكى ۋاقتىڭىزنى كۆپ ئىگىلىۋېلىشىغا يول قويماڭ." },
  { "text": "The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.", "translation": "قۇياشنىڭ ئۆزىمۇ تاڭ ئاتقاندا ئاجىز كېلىدۇ، لېكىن كۈننىڭ ئۆتۈشى بىلەن ئۇ كۈچ ۋە جەسارەت توپلايدۇ." },
  { "text": "You only live once, but if you do it right, once is enough.", "translation": "ھاياتقا بىرلا قېتىم كېلىسىز، ئەمما توغرا ياشىسىڭىز بىر قېتىممۇ يېتەرلىكتۇر." },
  { "text": "Life isn't about finding yourself. Life is about creating yourself.", "translation": "ھايات دېگەن ئۆزىڭىزنى تېپىش ئەمەس، بەلكى ئۆزىڭىزنى يارىتىشتۇر." },
  { "text": "For every minute you are angry you lose sixty seconds of happiness.", "translation": "سىز ئاچچىقلانغان ھەر بىر مىنۇتتا، 60 سېكۇنتلۇق خۇشاللىقىڭىزنى يوقىتىسىز." },
  { "text": "The best revenge is massive success.", "translation": "ئەڭ ياخشى ئۆچ ئېلىش — غايەت زور مۇۋەپپەقىيەت قازىنىشتۇر." }
];