window.hezine_turkish = [
  // 1-3: سىز تەمىنلىگەن ئاساسىي جۈملىلەر
  { "text": "Ne olursan ol, yine gel.", "translation": "كىم بولساڭ بول، يەنە كەل. (مەۋلانا)" },
  { "text": "Güneşin sana ulaşmasını istiyorsan gölgenden çık.", "translation": "قۇياشنىڭ ساڭا يېتىپ كېلىشىنى ئويلىساڭ، سايەڭدىن چىق." },
  { "text": "Sabır acıdır, ama meyvesi tatlıdır.", "translation": "سەۋىر ئاچچىقتۇر، ئەمما مېۋىسى تاتلىقتۇر." },

  // 4-20: ئىرادە، كۈرەش ۋە ئۈمىد
  { "text": "Hayat, fırtınanın geçmesini beklemek değil, yağmurda dans etmeyi öğrenmektir.", "translation": "ھايات بوران-چاپقۇننىڭ ئۆتۈپ كېتىشىنى كۈتۈش ئەمەس، بەلكى يامغۇردا ئۇسسۇل ئويناشنى ئۆگىنىشتۇر." },
  { "text": "Asla pes etme, çünkü bu, kaybedenlerin başvurduğu ilk ve son çaredir.", "translation": "ھەرگىز تەسلىم بولما، چۈنكى بۇ مەغلۇب بولغانلارنىڭ بىرىنچى ۋە ئاخىرقى چارىسىدۇر." },
  { "text": "En karanlık gece bile sona erer ve güneş yeniden doğar.", "translation": "ئەڭ قاراڭغۇ كېچىمۇ ئاخىرلىشىدۇ ۋە قۇياش قايتىدىن كۆتۈرۈلىدۇ." },
  { "text": "Her zorluk, içinde bir fırsat barındırır.", "translation": "ھەر بىر قىيىنچىلىقنىڭ ئىچىدە بىر پۇرسەت يوشۇرۇنغان." },
  { "text": "Güçlü olan, düşmeyen değil, düştüğünde kalkabilendir.", "translation": "كۈچلۈك دېگەن يىقىلمىغان ئەمەس، بەلكى يىقىلغاندا قايتا ئورنىدىن تۇرالىغاندۇر." },
  { "text": "Başlamak için en iyi zaman, şimdidir.", "translation": "باشلاشتىكى ئەڭ ياخشى ۋاقىت دەل ھازىردۇر." },
  { "text": "Unutma, her büyük başarı küçük bir adımla başlar.", "translation": "ئۇنتۇما، ھەر بىر بۈيۈك مۇۋەپپەقىيەت كىچىك بىر قەدەمدىن باشلىنىدۇ." },
  { "text": "Cesaret, korkmamak değil, korkuya rağmen devam etmektir.", "translation": "جاسارەت قورقماسلىق ئەمەس، بەلكى قورقۇنچقا قارىماي داۋام قىلىشتۇر." },
  { "text": "Rüzgara hakim olamıyorsan, yelkenlerini ona göre ayarla.", "translation": "شامالغا ھۆكۈمرانلىق قىلالمىساڭ، يەلكەنلىرىڭنى ئۇنىڭغا ماسلاشتۇر." },
  { "text": "İmkansız, sadece denemeyenlerin uydurduğu bir kelimedir.", "translation": "«مۇمكىن ئەمەس» دېگەن سۆز پەقەت سىناپ باقمىغانلار توقۇپ چىققان بىر سۆزدۇر." },
  { "text": "Yenilgi, vazgeçtiğin zaman başlar.", "translation": "مەغلۇبىيەت، ۋاز كەچكەن ۋاقتىڭدا باشلىنىدۇ." },
  { "text": "Yarınlar yorgun ve bezgin insanlara değil, rahatını terk edebilen cesur insanlara aittir.", "translation": "كەلگۈسى ھارغىن ۋە زېرىككەن كىشىلەرگە ئەمەس، بەلكى راھىتىدىن ۋاز كېچەلەيدىغان باتۇر كىشىلەرگە مەنسۇپتۇر." },
  { "text": "Umut, fakirin ekmeğidir.", "translation": "ئۈمىد، پېقىرنىڭ نېنىدۇر." },
  { "text": "Zirveye giden yol, engebeli yamaçlardan geçer.", "translation": "يۇقىرى پەللىگە چىقىدىغان يول، ئەگرى-بۈگرى قىيالاردىن ئۆتىدۇ." },
  { "text": "Eğer bir gün yolunu kaybedersen, bir çocuğun gözlerinin içine bak; çünkü bir çocuğun bir yetişkine öğretebileceği üç şey vardır: Nedensiz yere mutlu olmak, her zaman meşgul olabilecek bir şey bulmak ve elde etmek istediği şey için var gücüyle savaşmak.", "translation": "ئەگەر بىر كۈنى يولدىن ئېزىپ قالساڭ، بىر بالىنىڭ كۆزىگە قارا؛ چۈنكى بىر بالا چوڭلارغا ئۈچ نەرسىنى ئۆگىتەلەيدۇ: سەۋەبسىز بەختلىك بولۇش، ھەر دائىم ئۆزىنى ئالدىراش قىلىدىغان بىر ئىش تېپىش ۋە ئېرىشمەكچى بولغان نەرسىسى ئۈچۈن پۈتۈن كۈچى بىلەن كۈرەش قىلىش." },
  { "text": "Engeller, gözünüzü hedeften ayırdığınızda gördüğünüz o korkunç şeylerdir.", "translation": "توسالغۇلار، كۆزىڭىزنى نىشاندىن ئالغاندا كۆرىدىغان ئاشۇ قورقۇنچلۇق نەرسىلەردۇر." },

  // 21-40: ھايات، بەخت ۋە پەلسەپە
  { "text": "Hayat, satranç gibidir. Bir hamle yaparsın, bir sonraki hamle için beklersin.", "translation": "ھايات شاھماتقا ئوخشايدۇ. بىر قەدەم ماڭىسەن، ئاندىن كېيىنكى قەدەم ئۈچۈن كۈتىسەن." },
  { "text": "Mutluluk, sahip olduklarımızın toplamı değil, keyif aldıklarımızın toplamıdır.", "translation": "بەخت، ئىگە بولغانلىرىمىزنىڭ يىغىندىسى ئەمەس، بەلكى ھۇزۇرلانغانلىرىمىزنىڭ يىغىندىسىدۇر." },
  { "text": "Geçmiş bir anı, gelecek bir hayaldir. Tek gerçek, bugündür.", "translation": "ئۆتمۈش بىر ئەسلىمە، كەلگۈسى بىر خىيالدۇر. بىردىنبىر رېئاللىق بۈگۈندۇر." },
  { "text": "Hayatta en değerli hediye zamandır; kime verdiğine dikkat et.", "translation": "ھاياتتىكى ئەڭ قىممەتلىك سوۋغات ۋاقىتتۇر؛ ئۇنى كىمگە بېرىۋاتقىنىڭغا دىققەت قىل." },
  { "text": "Herkes ölür ama herkes gerçekten yaşamaz.", "translation": "ھەممە ئادەم ئۆلىدۇ، لېكىن ھەممە ئادەم ھەقىقىي مەنىدە ياشىمايدۇ." },
  { "text": "Kendini bilmek, tüm bilgeliğin başlangıcıdır.", "translation": "ئۆزىنى بىلىش، بارلىق دانالىقنىڭ باشلىنىشىدۇر." },
  { "text": "Küçük şeylerden mutlu olmayı öğrenemeyen, büyük şeylerle asla mutlu olamaz.", "translation": "كىچىك ئىشلاردىن خۇشال بولۇشنى ئۆگىنەلمىگەن كىشى، چوڭ ئىشلار بىلەن ھەرگىز خۇشال بولالمايدۇ." },
  { "text": "Hayat bisiklete binmek gibidir, dengeyi korumak için hareket etmeye devam etmelisiniz.", "translation": "ھايات ۋېلىسىپىت مىنىشكە ئوخشايدۇ، تەڭپۇڭلۇقنى ساقلاش ئۈچۈن توختىماي ھەرىكەت قىلىشىڭىز كېرەك." },
  { "text": "Gideceğin yeri bilmiyorsan, vardığın yerin önemi yoktur.", "translation": "نەگە بارىدىغىنىڭنى بىلمىسەڭ، يېتىپ بارغان جايىڭنىڭ ھېچقانداق ئەھمىيىتى يوق." },
  { "text": "En büyük zafer, insanın kendi nefsine karşı kazandığı zaferdir.", "translation": "ئەڭ چوڭ غەلىبە، ئىنساننىڭ ئۆز نەپسىگە قارشى ئېرىشكەن غەلىبىسىدۇر." },
  { "text": "Hayat, bir ayna gibidir. Gülümserseniz, o da size gülümser.", "translation": "ھايات ئەينەككە ئوخشايدۇ. ئەگەر كۈلۈمسىرىسىڭىز، ئۇمۇ سىزگە كۈلۈمسىرەيدۇ." },
  { "text": "Önemli olan, hayatta en çok şeye sahip olmak değil, en az şeye ihtiyaç duymaktır.", "translation": "مۇھىمى ھاياتتا ئەڭ كۆپ نەرسىگە ئىگە بولۇش ئەمەس، بەلكى ئەڭ ئاز نەرسىگە ئېھتىياجلىق بولۇشتۇر." },
  { "text": "Cahil ile sohbet etmek, ateşe odun taşımaktır.", "translation": "جاھىل بىلەن سۆھبەتلىشىش، ئوتقا ئوتۇن تېشىغانغا ئوخشايدۇ." },
  { "text": "Değişmeyen tek şey, değişimin kendisidir.", "translation": "ئۆزگەرمەيدىغان بىردىنبىر نەرسە، ئۆزگىرىشنىڭ ئۆزىدۇر." },
  { "text": "Akıllı insan, aklını kullanır. Daha akıllı insan, başkalarının da aklını kullanır.", "translation": "ئەقىللىق ئادەم ئۆز ئەقلىنى ئىشلىتىدۇ. تېخىمۇ ئەقىللىق ئادەم باشقىلارنىڭمۇ ئەقلىنى ئىشلىتىدۇ." },
  { "text": "İnsan, düşünen bir hayvandır.", "translation": "ئىنسان، تەپەككۇر قىلىدىغان بىر ھايۋاندۇر." },
  { "text": "Hayatı komedi sananlar, son espriyi iyi düşünsünler.", "translation": "ھاياتنى كومېدىيە دەپ ئويلايدىغانلار، ئەڭ ئاخىرقى چاقچاقنى ياخشى ئويلىسۇن." },
  { "text": "Kader, yolun tamamını değil, sadece yol ayrımlarını verir. Güzergah bellidir, ama tüm dönemeçler ve sapaklar yolcuya aittir.", "translation": "تەقدىر، يولنىڭ ھەممىسىنى ئەمەس، پەقەت يول ئايرىمىنىلا بېرىدۇ. يۆنىلىش ئېنىق، ئەمما بارلىق بۇرۇلۇشلار ۋە يول ئاغىزلىرى يولۇچىغا مەنسۇپتۇر." },
  { "text": "Düşünmek, ruhun kendi kendine konuşmasıdır.", "translation": "تەپەككۇر قىلىش، روھنىڭ ئۆز-ئۆزىگە سۆزلىشىدۇر." },

  // 41-60: بىلىم، سۆز ۋە سەنئەت
  { "text": "Okumak, gıdadır; okuyan insan, çok yemek yemiş insandır.", "translation": "ئوقۇش ئوزۇقتۇر؛ ئوقۇغان ئىنسان، كۆپ تاماق يېگەن ئىنساندۇر." },
  { "text": "Kalem, kılıçtan keskindir.", "translation": "قەلەم، قىلىچتىن ئۆتكۈردۇر." },
  { "text": "En iyi bildiğim şey, hiçbir şey bilmediğimdir.", "translation": "مەن ئەڭ ياخشى بىلىدىغان ئىش، ھېچنېمە بىلمەيدىغانلىقىمدۇر." },
  { "text": "Bir lisan, bir insan; iki lisan, iki insan.", "translation": "بىر تىل بىر ئىنسان؛ ئىككى تىل ئىككى ئىنسان." },
  { "text": "Söz gümüşse, sükût altındır.", "translation": "سۆز كۈمۈش بولسا، سۈكۈت ئالتۇندۇر." },
  { "text": "Cehalet, mutluluktur.", "translation": "جاھالەت، بەختتۇر. (كىنايىلىك مەنىدە)" },
  { "text": "Boş bir çuvalın dik durması zordur.", "translation": "قۇرۇق بىر خالتىنىڭ تىك تۇرۇشى تەس." },
  { "text": "Bilgi, paylaştıkça çoğalır.", "translation": "بىلىم، ھەمبەھىرلىگەنسېرى كۆپىيىدۇ." },
  { "text": "Müzik, ruhun gıdasıdır.", "translation": "مۇزىكا، روھنىڭ ئوزۇقىدۇر." },
  { "text": "Sanat, gerçeği anlamamızı sağlayan bir yalandır.", "translation": "سەنئەت، ھەقىقەتنى چۈشىنىشىمىزگە ياردەم بېرىدىغان بىر يالغانچىلىقتۇر." },
  { "text": "Anlamak, affetmektir.", "translation": "چۈشىنىش، كەچۈرۈش دېمەكتۇر." },
  { "text": "Sözler, en güçlü büyüdür.", "translation": "سۆزلەر، ئەڭ كۈچلۈك سېھىردۇر." },
  { "text": "Bir mum, diğer bir mumu tutuşturmakla ışığından bir şey kaybetmez.", "translation": "بىر شام، باشقا بىر شامنى ياندۇرۇش بىلەن ئۆز نۇرىدىن ھېچنېمە يوقاتمايدۇ." },
  { "text": "Her şeyin bir bedeli vardır.", "translation": "ھەممە نەرسىنىڭ بىر بەدىلى بار." },
  { "text": "En büyük savaş, cahilliğe karşı yapılan savaştır.", "translation": "ئەڭ بۈيۈك ئۇرۇش، جاھالەتكە قارشى ئېلىپ بېرىلغان ئۇرۇشتۇر." },
  { "text": "Kitapsız yaşamak, kör, sağır, dilsiz yaşamaktır.", "translation": "كىتابسىز ياشاش، كور، گاس ۋە تىلسىز ياشاشقا ئوخشايدۇ." },
  { "text": "Tarih, tekerrürden ibarettir.", "translation": "تارىخ، تەكرارلىنىشتىن ئىبارەتتۇر." },
  { "text": "İnsanı ateş değil, kendi gafleti yakar.", "translation": "ئىنساننى ئوت ئەمەس، ئۆز غەپلەتلىكى كۆيدۈرىدۇ." },
  { "text": "Güzel bakan, güzel görür.", "translation": "چىرايلىق قارىغان كىشى، چىرايلىق كۆرىدۇ." },

  // 61-80: مۇھەببەت، دوستلۇق ۋە ئىنسانىيەت
  { "text": "Sevmek, birbirine bakmak değil, birlikte aynı yöne bakmaktır.", "translation": "سۆيۈش، بىر-بىرىگە قاراش ئەمەس، بەلكى بىرلىكتە ئوخشاش بىر يۆنىلىشكە قاراشتۇر." },
  { "text": "Dost, kötü günde belli olur.", "translation": "دوست، قىيىن كۈندە بىلىنىدۇ." },
  { "text": "Aşk, iki bedende yaşayan tek bir ruhtan oluşur.", "translation": "مۇھەببەت، ئىككى بەدەندە ياشايدىغان بىر روھتىن تەركىب تاپقان." },
  { "text": "Yalnız taş, duvar olmaz.", "translation": "يالغۇز تاش، تام بولالمايدۇ." },
  { "text": "İnsan, insanın kurdudur.", "translation": "ئىنسان، ئىنساننىڭ بۆرىسىدۇر." },
  { "text": "Affetmek ve unutmak, iyi insanların intikamıdır.", "translation": "كەچۈرۈش ۋە ئۇنتۇش، ياخشى كىشىلەرنىڭ ئۆچ ئېلىشىدۇر." },
  { "text": "Gerçek dost, gölgen gibidir; eğilsen de doğrulsan da hep yanındadır.", "translation": "ھەقىقىي دوست سايەڭگە ئوخشايدۇ؛ ئېگىلسەڭمۇ، تىكلەنسەڭمۇ ھەمىشە يېنىڭدا بولىدۇ." },
  { "text": "Gülümseme, bulaşıcıdır.", "translation": "كۈلكە، يۇقۇملۇقتۇر." },
  { "text": "En iyi ayna, eski bir dosttur.", "translation": "ئەڭ ياخشى ئەينەك، كونا بىر دوستتۇر." },
  { "text": "Nefretle değil, sevgiyle kazanılır her savaş.", "translation": "ھەر بىر ئۇرۇش نەپرەت بىلەن ئەمەس، مۇھەببەت بىلەن غەلىبە قىلىنىدۇ." },
  { "text": "İyilik yap, denize at. Balık bilmezse, Halik bilir.", "translation": "ياخشىلىق قىل، دېڭىزغا تاشلا. بېلىق بىلمىسە، ياراتقۇچى (خالىق) بىلىدۇ." },
  { "text": "Yüzde ısrar etme, doksan da olur. İnsan dediğin, noksan da olur.", "translation": "يۈز بولسۇن دەپ چىڭ تۇرۇۋالما، توقسانمۇ بولىدۇ. ئىنسان دېگەن، كەمچىلىك بىلەنمۇ بولىدۇ." },
  { "text": "Kalp kırmak, Kabe'yi yıkmak gibidir.", "translation": "دىل ئاغرىتىش، كەبىنى چېقىشقا ئوخشايدۇ." },
  { "text": "Misafir, on kısmetle gelir, birini yer, dokuzunu bırakır.", "translation": "مېھمان ئون نېسىۋە بىلەن كېلىدۇ، بىرىنى يەيدۇ، توققۇزىنى قالدۇرۇپ كېتىدۇ." },
  { "text": "Komşu komşunun külüne muhtaçtır.", "translation": "قوشنا قوشنىنىڭ كۈلىگىمۇ موھتاج بولىدۇ." },
  { "text": "Ağaç yaşken eğilir.", "translation": "دەرەخ نەملىكىدە ئېگىلىدۇ. (بالىنى كىچىكىدە تەربىيەلەش كېرەك)" },
  { "text": "Bir elin nesi var, iki elin sesi var.", "translation": "بىر قولدىن نېمە كېلەر، ئىككى قولدىن ئاۋاز چىقىدۇ." },
  { "text": "Gözden ırak olan, gönülden de ırak olur.", "translation": "كۆزدىن يىراق بولغان، كۆڭۈلدىنمۇ يىراق بولىدۇ." },
  { "text": "Aç ayı oynamaz.", "translation": "ئاچ ئېيىق ئۇسسۇل ئوينىمايدۇ." },

  // 81-100: ئاخىرقى ئويلار ۋە ئىلھاملار
  { "text": "Ya olduğun gibi görün, ya da göründüğün gibi ol.", "translation": "يا قانداق بولساڭ شۇنداق كۆرۈن، ياكى قانداق كۆرۈنسەڭ شۇنداق بول." },
  { "text": "Damla damla göl olur.", "translation": "تامچە-تامچە كۆل بولۇر." },
  { "text": "Yavaş giden, yol alır.", "translation": "ئاستا ماڭغان، يول ئالىدۇ." },
  { "text": "Her şey olacağına varır.", "translation": "ھەممە ئىش ئۆز ۋاقتى-سائىتىدە بولىدۇ." },
  { "text": "Gülü seven, dikenine katlanır.", "translation": "گۈلنى سۆيگەن، تىكىنىگە بەرداشلىق بېرىدۇ." },
  { "text": "Kendi düşen ağlamaz.", "translation": "ئۆزى يىقىلغان يىغلىمايدۇ." },
  { "text": "Büyük balık, küçük balığı yutar.", "translation": "چوڭ بېلىق، كىچىك بېلىقنى يۇتىۋالىدۇ." },
  { "text": "Her yiğidin bir yoğurt yiyişi vardır.", "translation": "ھەر بىر باتۇرنىڭ بىر قېتىق يېيىش ئۇسۇلى بار. (ھەر كىمنىڭ ئۆزىگە خاس ئىش قىلىش ئۇسلۇبى بار)" },
  { "text": "Körle yatan, şaşı kalkar.", "translation": "كور بىلەن ياتقان، قارا چاپتۇل ئورنىدىن تۇرىدۇ." },
  { "text": "Zararın neresinden dönersen kardır.", "translation": "زىياننىڭ قەيېرىدىن قايتساڭ شۇ پايدىدۇر." },
  { "text": "Ateş olmayan yerden duman çıkmaz.", "translation": "ئوت بولمىغان يەردىن تۈتۈن چىقمايدۇ." },
  { "text": "Armut, dibine düşer.", "translation": "نەشپۈت، تۈۋىگە چۈشىدۇ." },
  { "text": "Sakla samanı, gelir zamanı.", "translation": "ساماننى ساقلاپ قوي، ۋاقتى كېلىدۇ." },
  { "text": "Acele işe şeytan karışır.", "translation": "ئالدىراش ئىشقا شەيتان ئارىلاشىدۇ." },
  { "text": "Tatlı dil, yılanı deliğinden çıkarır.", "translation": "تاتلىق تىل، يىلاننى ئۇۋىسىدىن چىقىرىدۇ." },
  { "text": "Lafla peynir gemisi yürümez.", "translation": "قۇرۇق گەپ بىلەن پىشلاق كېمىسى ماڭمايدۇ." },
  { "text": "El elden üstündür.", "translation": "قول قولدىن ئۈستۈندۇر." },
  { "text": "Zaman, her şeyin ilacıdır.", "translation": "ۋاقىت، ھەممە نەرسىنىڭ داۋاسىدۇر." },
  { "text": "Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiçbir zaman umudumu kaybetmedim.", "translation": "ئۈمىدسىز ئەھۋاللار يوق، پەقەت ئۈمىدسىز ئىنسانلار بار. مەن ھېچقاچان ئۈمىدىمنى يوقاتمىدىم. (مۇستافا كامال ئاتاتۈرك)" },
  { "text": "Hayat kısa, kuşlar uçuyor.", "translation": "ھايات قىسقا، قۇشلار ئۇچۇۋاتىدۇ. (جەمال سۈرەييا)" }
];